### ISSUE TITLE
[BUG] - Resetting issue filter causes infinite request loop

### ISSUE THREAD

**Issue by sudojunior** [Aru-Ku/hacktoberfest-issues#13]
### What bug or error did you encounter?

When the language filter is set back to it's default value, the value itself is set as the label `Filter by Language` and not undefined. _Page is stuck in an infinite loop, increasing requests exponentially as it progresses._

### What did you expect to happen?

Expected filter to be reset to `undefined` - as indicated by initial state, and it's associated interface.

https://github.com/Aru-Ku/hacktoberfest-issues/blob/14e79c5af44c3806dc1ca0be7b53330d7a77eee9/src/components/Forms/FilterForm.tsx#L5-L8

### Screenshots

![](https://interactions.is-serious.business/fmf2JFP.png)
> `console.log` statements to determine flow
> - `false` is the current value of `goodFirstIssue`
> - After that is the value of `language`

![](https://interactions.is-serious.business/6HBD9i1.png)
> After debugging with information below, and applying a bodged fix to `select$onChange`.

### Additional information

This value can be patched from it's selector (upon changing its state), but requires both forceful intervention. An empty string fulfils this criteria for the compiler to be satisfied without excluding the statement call.

https://github.com/Aru-Ku/hacktoberfest-issues/blob/14e79c5af44c3806dc1ca0be7b53330d7a77eee9/src/components/FormElements/Select.tsx#L33-L38

**Comment by Aru-Ku** [comment]
Hi @sudojunior 
Thank you for notifying about the bug.
Would you like to contribute on this ?

**Comment by sudojunior** [comment]
Considering the intended use of `undefined` for the initial option, I would like to see what someone else does with this...

> [`<option ...>` - w3.org](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-option-element.html) referring to the equivelent of a null coalescing default from `value` on `textContent`.
