### ISSUE TITLE
[Documentation] - Contributing.md and Code of Conduct files are missing !!

### ISSUE THREAD

**Issue by sumitbishti** [Aru-Ku/hacktoberfest-issues#2]
### What would you like to share?

Contributors.md and Code of Conduct files are missing as per the Hacktoberfest Guidelines.

I can create rich files with all the important guidelines of contributing towards the project.

Please assign this issue to me under Hacktoberfest.

**Comment by Aru-Ku** [comment]
Hi @sumitbishti 😀
I welcome you to make the contribution

**Comment by sumitbishti** [comment]
> Hi @sumitbishti 😀 I welcome you to make the contribution

Great! I'm on it.

**Comment by Aru-Ku** [comment]
closed by PR #6
