### ISSUE TITLE
[FEATURE REQUEST] - Containerize App

### ISSUE THREAD

**Issue by pythoninthegrass** [Aru-Ku/hacktoberfest-issues#20]
### Description of feature request, idea

Hi @Aru-Ku,

As a part of Hacktoberfest, looking to contribute to a few repos. If you'd like, I'd be happy to [Dockerize](https://docs.docker.com/language/nodejs/build-images/) your app for increased portability and easier deployment to web hosts.

Went ahead and forked the repo and will open a PR if you're interested.

Thank you,
Lance

**Comment by pythoninthegrass** [comment]
https://github.com/pythoninthegrass/hacktoberfest_issues/tree/container

**Comment by Aru-Ku** [comment]
Hi @pythoninthegrass 
Looks like, you are using [`npm run dev`](https://github.com/pythoninthegrass/hacktoberfest_issues/blob/container/Dockerfile#L20), this not recommended for production.

For more info on how to dockerize Next.JS application, refer [here](https://nextjs.org/docs/deployment#docker-image).
And here is the [sample Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile).

**Comment by pythoninthegrass** [comment]
Made the requested changes based on the first-party documents you listed along with community resources. Please see #22

**Comment by pythoninthegrass** [comment]
Thanks for merging the PR @Aru-Ku! If it's not too much trouble, please add the [hacktoberfest label](https://hacktoberfest.com/participation/#maintainers) to this issue 🙏

**Comment by Aru-Ku** [comment]
Ohh yeah, I forgot to add it.

**Comment by pythoninthegrass** [comment]
No worries! Thanks for the constructive feedback and web app. Really like the UI and it has the potential to be more useful than github's built-in filter.
