### ISSUE TITLE
[FEATURE REQUEST] - Filters the issues by labels and languages

### ISSUE THREAD

**Issue by Aru-Ku** [Aru-Ku/hacktoberfest-issues#3]
### Description of feature request, idea

Provide filtering options to filter issues based on repository language and labels (For example : bug, documentation, good first issue etc.)

**Comment by skar07** [comment]
Hey @Aru-Ku !
Would love to work on this, if you could assign the issue to me under hacktoberfest.

**Comment by sanny085** [comment]
I want to contribute on this issue.

**Comment by Aru-Ku** [comment]
Hi @skar07 
The basic UI for filters has been added. would you help on completing the remaining functionality.

**Comment by skar07** [comment]
@Aru-Ku Sure, I'll have a look and help with the remaining functionality.
