### ISSUE TITLE
[BUG] - Selecting a programming language from the dropdown does not update the list

### ISSUE THREAD

**Issue by princefishthrower** [Aru-Ku/hacktoberfest-issues#9]
### What bug or error did you encounter?

Unless I misunderstand the dropdown, the issue I see is as the title states: the list is not filtered according to the language I select. (and subsequent pages of the list that are loaded also do not meet the filter)

### What did you expect to happen?

Only repositories that include my selected language should appear.

### Additional information

More of a feature request than a bug, but directly relevant: It may also be prudent to make, instead of a dropdown, a list of selectable chips of languages (rendered as they are on the cards). This way I can select multiple languages I know instead of just one.

**Comment by Aru-Ku** [comment]
Actually, this is feature has not yet been developed. It is still in progress

**Comment by princefishthrower** [comment]
Ah, my mistake, I didn't see https://github.com/Aru-Ku/hacktoberfest-issues/issues/3
